export const APP_TEXTS = {
  eyebrow: 'FORMS / BUILDER',
  savedEyebrow: 'SAVED SUCCESSFULLY',
  title: 'בונה תבניות טפסים',
  subtitle: 'הרכיבו טופס, הגדירו שדות וסדרו מסלול אישורים ברור.',
  formDetails: 'פרטי הטופס',
  formName: 'שם הטופס',
  formNamePlaceholder: 'למשל: בקשת רכש',
  createdBy: 'נוצר על ידי',
  userIdPlaceholder: 'מזהה משתמש',
  fields: 'שדות',
  fieldsCount: 'שדות',
  addTextField: '+ הוסף שדה טקסט',
  addDateField: '+ הוסף שדה תאריך',
  chooseFieldType: 'בחרו סוג שדה כדי להתחיל לבנות את הטופס.',
  fieldLabelPlaceholder: 'תווית השדה',
  required: 'חובה',
  removeField: 'הסר שדה',
  approvalSteps: 'מסלול אישורים',
  addStep: '+ הוסף שלב',
  noApprovalSteps: 'אין שלבי אישור. הוסיפו שלב כדי להגדיר מי מאשר את הטופס.',
  stepNamePlaceholder: 'שם שלב',
  actionTypePlaceholder: 'סוג הפעולה',
  approve: 'אישור',
  reject: 'דחייה',
  removeStep: 'הסר שלב',
  saveTemplate: 'שמור תבנית',
  saving: 'שומר...',
  saved: 'הטופס נוצר בהצלחה',
  savedDescription: 'התבנית נשמרה במערכת וזמינה כעת ברשימת התבניות.',
  understood: 'הבנתי',
  myTemplates: 'התבניות שלי',
  recentlySaved: 'תבניות שנשמרו לאחרונה',
  templateEmpty: 'התבניות שתשמרו יופיעו כאן.',
  addApprovalSteps: '+ הוסף שלבי אישורים',
  approvalEditor: 'הוספת שלבי אישורים',
  approvalEditorDescription: 'הגדירו את סדר השלבים, המאשר והפעולה המותרת.',
  cancel: 'ביטול',
  saveApprovalSteps: 'שמור שלבי אישור',
  approvalSaved: 'שלבי האישור נשמרו בהצלחה',
  validationError: 'יש למלא את כל השדות הנדרשים לפני השמירה',
  approvalValidationError: 'יש למלא את כל פרטי שלבי האישור',
  templateSaveError: 'שמירת הטופס נכשלה',
  approvalSaveError: 'שמירת שלבי האישור נכשלה',
  loadError: 'לא ניתן לטעון את תבניות הטפסים',
  fieldTypeLabels: { Text: 'Text field', Date: 'Date field' }
} as const;